//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusquedaDeParejas.Idiomas {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class recurso {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal recurso() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BusquedaDeParejas.Idiomas.recurso", typeof(recurso).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a DIFÍCIL.
        /// </summary>
        internal static string btDificil {
            get {
                return ResourceManager.GetString("btDificil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a FÁCIL.
        /// </summary>
        internal static string btFacil {
            get {
                return ResourceManager.GetString("btFacil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a INICIAR.
        /// </summary>
        internal static string btIniciar {
            get {
                return ResourceManager.GetString("btIniciar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a MEDIO.
        /// </summary>
        internal static string btMedio {
            get {
                return ResourceManager.GetString("btMedio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SALIR.
        /// </summary>
        internal static string btSalir {
            get {
                return ResourceManager.GetString("btSalir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ESPAÑOL.
        /// </summary>
        internal static string cbEspañol {
            get {
                return ResourceManager.GetString("cbEspañol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a INGLÉS.
        /// </summary>
        internal static string cbIngles {
            get {
                return ResourceManager.GetString("cbIngles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a DIFICULTAD.
        /// </summary>
        internal static string lbDificultad {
            get {
                return ResourceManager.GetString("lbDificultad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a IDIOMA.
        /// </summary>
        internal static string lbIdioma {
            get {
                return ResourceManager.GetString("lbIdioma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a JUGADOR.
        /// </summary>
        internal static string lbJugador {
            get {
                return ResourceManager.GetString("lbJugador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SEGUNDOS.
        /// </summary>
        internal static string lbSegundos {
            get {
                return ResourceManager.GetString("lbSegundos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a TIENES QUE COMPLETAR EL NOMBRE.
        /// </summary>
        internal static string String1 {
            get {
                return ResourceManager.GetString("String1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a TIENES QUE ESCOGER DIFICULTAD.
        /// </summary>
        internal static string String2 {
            get {
                return ResourceManager.GetString("String2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡GENIAL, LO HAS LOGRADO!.
        /// </summary>
        internal static string String3 {
            get {
                return ResourceManager.GetString("String3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡HAS AGOTADO TU TIEMPO!.
        /// </summary>
        internal static string String4 {
            get {
                return ResourceManager.GetString("String4", resourceCulture);
            }
        }
    }
}
